### ISSUE TITLE
Configure Guide?

### ISSUE THREAD

**Issue by dropitlikecross** [oppaoppai/animeandromeda-python#1]
Hello, could you please provide a configuration guide?

Thank you <3

**Comment by oppaoppai** [comment]
Hi there, sure I'll provide a startup guide as soon as I finish some Uni stuff

**Comment by oppaoppai** [comment]
Hi, I've updated the "readme.md" with the configuration guide as you asked.

**Comment by dropitlikecross** [comment]
Thank you very much! Also thank you for adding your contact. I'll reach out after I play with it a bit. 😁
